Testing
ToxicButterfly/PassengerService pull request #5
Opened 2024-02-21 16:34 UTC by ToxicButterfly

2024-02-26 07:29 UTC, przhevvalsky requested changes

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
>  import org.springframework.web.bind.annotation.*;
fix wildcard import

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
> +    final PassengerForRidesService ridesService;
private забыл добавить

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
> +    public ResponseEntity<PassengerDto> registration(@RequestBody @Valid Passenger passenger) {
у тебя есть PassengerDto, но ты его почему-то не используешь. На то есть какая-то причина?

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
>      }
логика связанная с секюрити должна быть в отдельном сервисе, у вас по архитектуре приложения это предусмотрено, пересмотри

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
> +    public ResponseEntity<PassengerDto> updatePassenger(@RequestBody @Valid Passenger passenger, @PathVariable int id) {
DTO pattern

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
> +    }
вся логика с поездками, по-хорошему, должна находиться в rides-service

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/dto/BankDataDto.java
> +import lombok.*;
fix wildcard import

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/model/Passenger.java
>      private String password;
passenger-service не должен хранить логины и пароли юзеров

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +    final PassengerDtoConverter passengerDtoConverter;
почему нет private, если есть на то какая-то причина, то рад был бы узнать))

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +    }
не очень понимаю смысл этого метода, он же всегда возвращает одни и те же данные

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +        int r = 1 + random.nextInt(5);
в приватный метод надо выносить ту логику, которая может со временем меняться

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +        Passenger passenger = passengerRepo.findById(id).get();
так optional-ы не обрабатывают.

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/util/Messages.java
> +    public final Float BALANCE = 90000F;
что это такое, ты же не тесты пишешь)

2024-02-26 07:29 UTC, przhevvalsky commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/passengerdb
move host to environment

2024-02-26 07:29 UTC, przhevvalsky commented on src/test/java/com/example/passengerservice/controller/IntegrationTestStructure.java
> +
??

2024-03-04 16:37 UTC, ToxicButterfly commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
> +    public ResponseEntity<PassengerDto> registration(@RequestBody @Valid Passenger passenger) {
Passenger для хранения всех данных пассажира, PassengerDto для передачи безопасных данных, которые не страшно раскрыть

2024-03-04 16:38 UTC, ToxicButterfly commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
>      }
Секьюрити последняя тема, там переделаю и логику регистрации

2024-03-04 16:45 UTC, ToxicButterfly commented on src/main/java/com/example/passengerservice/model/Passenger.java
>      private String password;
Почему? Сервис пассажиров отвечает за логику данных пассажиров

2024-03-04 16:46 UTC, ToxicButterfly commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +    final PassengerDtoConverter passengerDtoConverter;
Только моя забывчивость)

2024-03-04 16:47 UTC, ToxicButterfly commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +    }
Просто заглушка, для данных банковской карты пассажиров

2024-03-04 16:51 UTC, ToxicButterfly commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +        Passenger passenger = passengerRepo.findById(id).get();
Да, но пассажир с этим айди уже вызвал такси, и после поездки рейтинг пассажира с этим айди будет обновлён. Надо ли проверять на наличие после поездки?

2024-03-04 17:11 UTC, ToxicButterfly commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/passengerdb
В смысле?

2024-03-05 09:02 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/controller/PassengerController.java
> +    public ResponseEntity<PassengerDto> registration(@RequestBody @Valid Passenger passenger) {
@ToxicButterfly, начнём с того, что DTO паттерн, в первую очередь, не про "безопасные данные", а про "передачу". Любые данные, которые ты получил с БД, ты оборачиваешь в DTO и отправляешь клиенту, тоже самое касается принятия данных от клиента. У тебя Passenger содержит поля, которые абсолютно **не используются** твоим клиентом. Зачем клиенту давать возможность вводить те поля(rating, id), логика заполнения которых может лежать или на БД или на твоих сервисах? Со временем структура основных классов(это твои @Entity-классы) будет меняться, мб кто-то захочет добавить парочку новых полей, к примеру, createdAt и тд; и ты продолжишь кидать клиету этот свой огромный класс, где тебе максимум надо парочку полей? Ты говоришь про безопасность, разве безопасно в случае, когда клиент хочет обновить какую-то инфу о себе, давать ему возможность обновить вообще все поля, которые должны быть скрыты для него(это для update метода, где ты тоже передаёшь целиком сущность Passenger)?

Контракт определяет модель данных, которая должна быть передана в контроллер, но контракт **не должен** являться бизнес-сущности.

И это далеко не все моменты почему тебе нужно dto, попробуй углубиться в эту тему и почитать почему плохо давать клиенту целую сущность, когда ему надо буквально пару полей).

2024-03-05 10:33 UTC, NikPrg commented on src/main/java/com/example/passengerservice/model/Passenger.java
>      private String password;
@ToxicButterfly, да, всё верно, но а для чего тогда тебе нужен auth server?
у passenger-service нету респонсибилити заниматься аутентификацией, это лежит на плечах auth server, следовательно пароли твои будут храниться там

2024-03-05 10:36 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +        Passenger passenger = passengerRepo.findById(id).get();
@ToxicButterfly, да, всё верно, но а для чего тогда тебе нужен auth server?
у passenger-service нету респонсибилити заниматься аутентификацией, это лежит на плечах auth server, следовательно пароли твои будут храниться там

2024-03-05 10:37 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/model/Passenger.java
>      private String password;
@ToxicButterfly, да, всё верно, но а для чего тогда тебе нужен auth server?
у passenger-service нету респонсибилити заниматься аутентификацией, это лежит на плечах auth server, следовательно пароли твои будут храниться там

2024-03-05 10:38 UTC, przhevvalsky commented on src/main/java/com/example/passengerservice/service/impl/PassengerServiceImpl.java
> +        Passenger passenger = passengerRepo.findById(id).get();
Мало ли что там может случиться с этим пассажиром, проверять его наличие обязательно нужно

2024-03-05 10:40 UTC, przhevvalsky commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/passengerdb
@ToxicButterfly, свой хост - 5432 вынеси в .env файл, чтобы проще было менять, в случе если кому-то это потребуется

2024-03-20 15:18 UTC, merged